spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/springbootkotlinjpa
    username: sa
    password :
    deriver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
Loggin:
  level:
    org.hibernate.SQL: debug
